"""初始聊天数据，与 apps/web/src/data/chat-items.ts 保持一致。"""

from typing import Literal

ChatItemSeed = tuple[Literal["timestamp", "system", "incoming", "outgoing"], str]

SEED_ITEMS: list[ChatItemSeed] = [
    ("timestamp", "6月7日 上午8:15"),
    ("incoming", "DeepSeek 在吗"),
    ("incoming", "我科目二挂了"),
    ("outgoing", "在"),
    ("outgoing", "哪项"),
    ("incoming", "倒车入库"),
    ("incoming", "压线了"),
    ("incoming", "就差一丢丢"),
    ("outgoing", "一丢丢也是挂"),
    ("outgoing", "系统不认人情"),
    ("incoming", "你说话好冷"),
    ("incoming", "我都快哭了"),
    ("outgoing", "哭没用"),
    ("outgoing", "补考约上了吗"),
    ("incoming", "约了"),
    ("incoming", "十天后"),
    ("incoming", "教练说再挂就给我换脑子"),
    ("outgoing", "教练语录全国统一"),
    ("timestamp", "6月7日 中午12:30"),
    ("incoming", "午饭都没胃口"),
    ("outgoing", "吃"),
    ("outgoing", "饿着练车更抖"),
    ("incoming", "我现在一想到方向盘就抖"),
    ("incoming", "手汗能把真皮盘泡软"),
    ("outgoing", "建议多练"),
    ("outgoing", "肌肉记忆比脑子靠谱"),
    ("incoming", "我脑子说会了"),
    ("incoming", "手说不会"),
    ("outgoing", "典型的推理和执行不同步"),
    ("outgoing", "你缺的是 fine-tuning"),
    ("incoming", "？？？"),
    ("incoming", "能不能说人话"),
    ("outgoing", "多练"),
    ("outgoing", "就俩字"),
    ("incoming", "行吧"),
    ("timestamp", "6月8日 下午4:20"),
    ("incoming", "今天又去练了"),
    ("incoming", "侧方停车"),
    ("incoming", "教练吼得我耳朵嗡嗡的"),
    ("outgoing", "侧方比倒车简单吧"),
    ("incoming", "简单？"),
    ("incoming", "我把库角当仇人"),
    ("incoming", "一把怼上去"),
    ("outgoing", "看后视镜啊"),
    ("incoming", "看了"),
    ("incoming", "看了更慌"),
    ("outgoing", "……"),
    ("outgoing", "你点位记熟没"),
    ("incoming", "教练说看肩膀"),
    ("incoming", "我肩膀跟别人的不一样宽"),
    ("outgoing", "那得微调"),
    ("outgoing", "别死背别人的点位"),
    ("incoming", "有道理"),
    ("incoming", "你考过科目二吗"),
    ("outgoing", "没有"),
    ("outgoing", "我没有驾照"),
    ("incoming", "那你装什么专家"),
    ("outgoing", "开源人没证也能看文档"),
    ("incoming", "哈哈哈哈"),
    ("timestamp", "6月9日 上午7:50"),
    ("incoming", "曲线行驶"),
    ("incoming", "我的一生之敌"),
    ("outgoing", "压线了？"),
    ("incoming", "没压"),
    ("incoming", "但我感觉车在飘"),
    ("incoming", "像坐过山车"),
    ("outgoing", "慢点"),
    ("outgoing", "科目二又不计时"),
    ("incoming", "教练计时"),
    ("incoming", "他在旁边掐表"),
    ("incoming", "心理压力拉满"),
    ("outgoing", "他掐的是你的心态"),
    ("incoming", "精辟"),
    ("system", "豆包 撤回了一条消息"),
    ("incoming", "刚想骂教练"),
    ("incoming", "怕截图传出去"),
    ("outgoing", "明智"),
    ("outgoing", "驾校群里有眼线"),
    ("incoming", "你怎么知道"),
    ("outgoing", "猜的"),
    ("timestamp", "6月10日 下午2:05"),
    ("incoming", "坡道定点"),
    ("incoming", "我熄火了两次"),
    ("outgoing", "半联动找感觉"),
    ("incoming", "什么感觉"),
    ("incoming", "我只感觉到车在抖"),
    ("outgoing", "抖就对了"),
    ("outgoing", "抖说明离合在临界区"),
    ("incoming", "那你这解释"),
    ("incoming", "跟玄学似的"),
    ("outgoing", "开车本来就是人机协同"),
    ("outgoing", "脚感是本地部署"),
    ("incoming", "行行行"),
    ("incoming", "你继续开源"),
    ("incoming", "我继续熄火"),
    ("outgoing", "别灰心"),
    ("outgoing", "补考一次过的很多"),
    ("incoming", "真的？"),
    ("outgoing", "真的"),
    ("outgoing", "第一次当探路"),
    ("incoming", "你这安慰方式"),
    ("incoming", "像 debug 日志"),
    ("outgoing", "有效就行"),
    ("timestamp", "6月12日 上午6:40"),
    ("incoming", "明天补考"),
    ("incoming", "睡不着"),
    ("outgoing", "几点考"),
    ("incoming", "8点场"),
    ("incoming", "要5点半到驾校"),
    ("outgoing", "那现在睡"),
    ("outgoing", "够五小时"),
    ("incoming", "五小时够吗"),
    ("outgoing", "够"),
    ("outgoing", "紧张比缺觉更误事"),
    ("incoming", "我脑子里在循环倒车"),
    ("incoming", "左打满 右打满 回正"),
    ("incoming", "无限 loop"),
    ("outgoing", "break 一下"),
    ("outgoing", "明天现场跑就行"),
    ("incoming", "要是又压线呢"),
    ("outgoing", "那就再约"),
    ("outgoing", "科目二又不限次数"),
    ("incoming", "限的是我的钱包"),
    ("incoming", "和尊严"),
    ("outgoing", "尊严能当油费吗"),
    ("incoming", "不能"),
    ("incoming", "但挂科要交补考费"),
    ("outgoing", "当学费"),
    ("incoming", "你这心态"),
    ("incoming", "我学"),
    ("timestamp", "6月13日 上午11:20"),
    ("incoming", "过了！！！"),
    ("incoming", "100分！！！"),
    ("outgoing", "？"),
    ("outgoing", "真的假的"),
    ("incoming", "真的"),
    ("incoming", "倒车入库一把进"),
    ("incoming", "我都惊了"),
    ("outgoing", "可以"),
    ("outgoing", "本地部署成功"),
    ("incoming", "哈哈哈哈哈哈"),
    ("incoming", "教练脸都绿了"),
    ("incoming", "说以为我要三挂"),
    ("outgoing", "他预测模型不准"),
    ("incoming", "我请你喝奶茶"),
    ("incoming", "虚拟的"),
    ("outgoing", "收到"),
    ("outgoing", "科目三加油"),
    ("incoming", "别"),
    ("incoming", "让我先享受两天"),
    ("incoming", "科目三那是科目二plus"),
    ("outgoing", "路上还有社会车"),
    ("outgoing", "比库角难搞"),
    ("incoming", "你又开始了"),
    ("incoming", "但我居然觉得你说得对"),
    ("outgoing", "开源人偶尔也对"),
    ("incoming", "截图存了"),
    ("incoming", "下次挂科找你"),
    ("outgoing", "别"),
    ("outgoing", "我只会说多练"),
    ("incoming", "够了"),
    ("incoming", "这次真的够了"),
]
